- id: nextflow-lint
  name: Nextflow Lint
  description: Run nextflow lint on Nextflow pipeline files
  entry: nextflow-lint-hook
  language: script
  files: \.nf$
  require_serial: true
  pass_filenames: false
  always_run: false 