name: Test Nextflow Lint Pre-commit Hook

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]
  workflow_dispatch:

jobs:
  test:
    name: Test Hook
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        nextflow-version: ["25.04.6", "latest"]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Nextflow
        uses: nf-core/setup-nextflow@v2
        with:
          version: ${{ matrix.nextflow-version }}

      - name: Make hook executable
        run: chmod +x nextflow-lint-hook

      - name: Test basic functionality
        run: |
          # Test with no files (should exit cleanly)
          ./nextflow-lint-hook

          # Create valid test file
          cat > test.nf << 'EOF'
          #!/usr/bin/env nextflow
          nextflow.enable.dsl = 2

          process test {
              output: stdout
              script: "echo 'test'"
          }

          workflow { test() }
          EOF

          # Create config file
          cat > nextflow.config << 'EOF'
          params {
              input = 'test'
              output = 'results'
          }
          EOF

          # Create config file
          cat > nextflow.config << 'EOF'
          params {
              input = 'test'
              output = 'results'
          }
          EOF

          # Test basic linting
          ./nextflow-lint-hook

          # Test with arguments
          ./nextflow-lint-hook -output concise
          ./nextflow-lint-hook -format

      - name: Test invalid file handling
        run: |
          # Create invalid file
          cat > invalid.nf << 'EOF'
          #!/usr/bin/env nextflow
          process bad { script: "echo test"
          EOF

          # Should fail with invalid syntax
          if ./nextflow-lint-hook; then
            echo "Should have failed"
            exit 1
          fi

  test-pre-commit:
    name: Test Pre-commit Integration
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          pip install pre-commit
          curl -s https://get.nextflow.io | bash
          sudo mv nextflow /usr/local/bin/

      - name: Make hook executable
        run: chmod +x nextflow-lint-hook

      - name: Test pre-commit integration
        run: |
          # Create test config
          cat > .pre-commit-config.yaml << 'EOF'
          repos:
            - repo: local
              hooks:
                - id: nextflow-lint
                  name: Nextflow Lint
                  entry: ./nextflow-lint-hook
                  language: script
                  files: \.nf$
          EOF

          # Create test file
          cat > main.nf << 'EOF'
          #!/usr/bin/env nextflow
          nextflow.enable.dsl = 2

          process test {
              output: stdout
              script: "echo 'test'"
          }

          workflow { test() }
          EOF

          # Test pre-commit
          pre-commit run --all-files

  test-no-nextflow:
    name: Test Without Nextflow
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Make hook executable
        run: chmod +x nextflow-lint-hook

      - name: Test graceful failure
        run: |
          echo '#!/usr/bin/env nextflow\nprocess test { script: "echo test" }' > test.nf

          # Should fail gracefully without Nextflow
          if ./nextflow-lint-hook; then
            echo "Should have failed without Nextflow"
            exit 1
          fi
